version: 2
updates:
  - package-ecosystem: nuget
    directory: /ElaroAPI/ElaroApi
    groups:
      dotnet-dependencies:
        patterns:
          - "*"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Istanbul

  - package-ecosystem: gradle
    directory: /ElaroMobil
    groups:
      android-dependencies:
        patterns:
          - "*"
    schedule:
      interval: weekly
      day: monday
      time: "06:15"
      timezone: Europe/Istanbul

  - package-ecosystem: github-actions
    directory: /
    groups:
      github-actions:
        patterns:
          - "*"
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: Europe/Istanbul
